# https://www.codacy.com/app/gaujin/tornado-crontab/dashboard
engines:
    radon:
        enabled: true
        config:
            threshold: 'B'
    pep8:
        enabled: true
ratings:
    paths:
    - "**.py"
exclude_paths:
- "tests/*"
- "setup.py"
