# https://codeclimate.com/github/gaujin/tornado-crontab
engines:
    radon:
        enabled: true
        config:
            threshold: 'B'
    pep8:
        enabled: true
ratings:
    paths:
    - "tornado_crontab/**.py"
