# https://travis-ci.org/gaujin/tornado-crontab
language: python
python:
    - "2.7"
    - "pypy2.7-5.8.0"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "3.8-dev"
    - "nightly"
    - "pypy3.5-5.8.0"
install: "pip install -r requirements.txt"
script: nosetests -v
