# https://ci.appveyor.com/project/gaujin/tornado-crontab
environment:
  matrix:
    - PYTHON: "C:/Python26"
    - PYTHON: "C:/Python26-x64"
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python33"
    - PYTHON: "C:/Python33-x64"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python34-x64"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python35-x64"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

version: '#{build}'

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

build: false

test_script:
  - "%PYTHON%/Scripts/nosetests.exe -v"
